import Foundation

/// ESS-571 Wave 0: Unified event envelope for the realtime media protocol.
///
/// The envelope carries the four-level identity system defined in the ESS-543
/// technical design v1.2 §1.1:
///
/// | Identifier          | Lifecycle                                          | Generated by              |
/// |---------------------|----------------------------------------------------|---------------------------|
/// | `conversation_id`   | Tap orb → X / 10 min / lifecycle termination       | Watch ConversationHandle  |
/// | `turn_id`           | A single user utterance, from speech → VAD final   | Watch UUIDv7              |
/// | `generation_id`     | One Qwen generation attempt for a turn             | Gateway UUIDv7            |
/// | `response_id`       | One logical response (text + audio + done)          | Gateway UUIDv7            |
///
/// Compatibility: during migration, the envelope coexists with the existing
/// `session_id`/`request_id` flat-wire fields.
///
/// ### Wire shape
///
/// ```json
/// {
///   "schema_version": 1,
///   "event_id": "uuidv7",
///   "conversation_id": "uuidv7",
///   "turn_id": "uuidv7",
///   "generation_id": "uuidv7|null",
///   "response_id": "uuidv7|null",
///   "seq": 17,
///   "type": "input_audio.delta",
///   "created_at_ms": 1786123456789,
///   "payload": {}
/// }
/// ```
struct RealtimeEventEnvelope: Equatable, Sendable {

    static let currentSchemaVersion = 1

    let schemaVersion: Int
    let eventId: String
    let conversationId: String
    let turnId: String
    let generationId: String?
    let responseId: String?
    let seq: Int
    let type: String
    let createdAtMs: Int64
    /// Raw JSON payload. Sendable-safe (Data is Sendable).
    /// Use `payloadDict()` to access decoded keys.
    let payload: Data

    // MARK: - Init

    init(
        schemaVersion: Int = Self.currentSchemaVersion,
        eventId: String = UUIDv7.generate().uuidString,
        conversationId: String,
        turnId: String,
        generationId: String? = nil,
        responseId: String? = nil,
        seq: Int,
        type: String,
        createdAtMs: Int64 = Int64(Date().timeIntervalSince1970 * 1_000),
        payload: Data = Data()
    ) {
        self.schemaVersion = schemaVersion
        self.eventId = eventId
        self.conversationId = conversationId
        self.turnId = turnId
        self.generationId = generationId
        self.responseId = responseId
        self.seq = seq
        self.type = type
        self.createdAtMs = createdAtMs
        self.payload = payload
    }

    /// Convenience init that accepts a dictionary payload.
    init(
        schemaVersion: Int = Self.currentSchemaVersion,
        eventId: String = UUIDv7.generate().uuidString,
        conversationId: String,
        turnId: String,
        generationId: String? = nil,
        responseId: String? = nil,
        seq: Int,
        type: String,
        createdAtMs: Int64 = Int64(Date().timeIntervalSince1970 * 1_000),
        payloadDict: [String: Any]
    ) {
        self.init(
            schemaVersion: schemaVersion,
            eventId: eventId,
            conversationId: conversationId,
            turnId: turnId,
            generationId: generationId,
            responseId: responseId,
            seq: seq,
            type: type,
            createdAtMs: createdAtMs,
            payload: Self.serializePayload(payloadDict)
        )
    }

    // MARK: - Payload access

    /// Access the payload as a decoded dictionary.
    func payloadDict() -> [String: Any] {
        Self.deserializePayload(payload)
    }

    private static func serializePayload(_ dict: [String: Any]) -> Data {
        guard !dict.isEmpty,
              let data = try? JSONSerialization.data(withJSONObject: dict, options: [.sortedKeys])
        else { return Data() }
        return data
    }

    private static func deserializePayload(_ data: Data) -> [String: Any] {
        guard !data.isEmpty,
              let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return [:] }
        return dict
    }

    // MARK: - Decode

    static func decode(from dict: [String: Any]) -> RealtimeEventEnvelope? {
        guard let schemaVersion = dict["schema_version"] as? Int,
              let eventId = dict["event_id"] as? String,
              let conversationId = dict["conversation_id"] as? String,
              let turnId = dict["turn_id"] as? String,
              let seq = dict["seq"] as? Int,
              let type = dict["type"] as? String,
              let createdAtMs = dict["created_at_ms"] as? Int64
        else { return nil }
        let createdAt: Int64 = createdAtMs > 0 ? createdAtMs
            : Int64((dict["created_at_ms"] as? Int) ?? 0)

        let generationId = dict["generation_id"] as? String
        let responseId = dict["response_id"] as? String
        let payloadDict = (dict["payload"] as? [String: Any]) ?? [:]

        return RealtimeEventEnvelope(
            schemaVersion: schemaVersion,
            eventId: eventId,
            conversationId: conversationId,
            turnId: turnId,
            generationId: generationId,
            responseId: responseId,
            seq: seq,
            type: type,
            createdAtMs: createdAt,
            payloadDict: payloadDict
        )
    }

    static func decode(from data: Data) -> RealtimeEventEnvelope? {
        guard let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return nil }
        return decode(from: dict)
    }

    static func decode(from text: String) -> RealtimeEventEnvelope? {
        guard let data = text.data(using: .utf8) else { return nil }
        return decode(from: data)
    }

    // MARK: - Encode

    func encode() -> [String: Any] {
        var dict: [String: Any] = [
            "schema_version": schemaVersion,
            "event_id": eventId,
            "conversation_id": conversationId,
            "turn_id": turnId,
            "seq": seq,
            "type": type,
            "created_at_ms": createdAtMs
        ]
        if let gid = generationId { dict["generation_id"] = gid }
        if let rid = responseId { dict["response_id"] = rid }
        if !payload.isEmpty, let payloadObj = try? JSONSerialization.jsonObject(with: payload) {
            dict["payload"] = payloadObj
        }
        return dict
    }

    func encodeToString() -> String? {
        guard let data = try? JSONSerialization.data(
            withJSONObject: encode(),
            options: [.sortedKeys]
        ) else { return nil }
        return String(data: data, encoding: .utf8)
    }

    func encodeToData() -> Data? {
        try? JSONSerialization.data(withJSONObject: encode(), options: [.sortedKeys])
    }

    // MARK: - Equatable

    static func == (lhs: RealtimeEventEnvelope, rhs: RealtimeEventEnvelope) -> Bool {
        lhs.schemaVersion == rhs.schemaVersion
        && lhs.eventId == rhs.eventId
        && lhs.conversationId == rhs.conversationId
        && lhs.turnId == rhs.turnId
        && lhs.generationId == rhs.generationId
        && lhs.responseId == rhs.responseId
        && lhs.seq == rhs.seq
        && lhs.type == rhs.type
        && lhs.createdAtMs == rhs.createdAtMs
    }

    // MARK: - Factory helpers

    static func inputAudioDelta(
        conversationId: String,
        turnId: String,
        seq: Int,
        audioBase64: String,
        sampleRate: Int = 16_000,
        codec: String = "pcm_s16le"
    ) -> RealtimeEventEnvelope {
        RealtimeEventEnvelope(
            conversationId: conversationId,
            turnId: turnId,
            seq: seq,
            type: "input_audio.delta",
            payloadDict: [
                "audio": audioBase64,
                "sample_rate": sampleRate,
                "codec": codec
            ]
        )
    }

    static func responseAudioDelta(
        conversationId: String,
        turnId: String,
        generationId: String,
        responseId: String,
        seq: Int,
        audioBase64: String,
        sampleRate: Int = 24_000,
        codec: String = "pcm_s16le"
    ) -> RealtimeEventEnvelope {
        RealtimeEventEnvelope(
            conversationId: conversationId,
            turnId: turnId,
            generationId: generationId,
            responseId: responseId,
            seq: seq,
            type: "response.audio.delta",
            payloadDict: [
                "audio": audioBase64,
                "sample_rate": sampleRate,
                "codec": codec
            ]
        )
    }

    static func responseDone(
        conversationId: String,
        turnId: String,
        generationId: String,
        responseId: String,
        seq: Int
    ) -> RealtimeEventEnvelope {
        RealtimeEventEnvelope(
            conversationId: conversationId,
            turnId: turnId,
            generationId: generationId,
            responseId: responseId,
            seq: seq,
            type: "response.done"
        )
    }

    static func responseCancel(
        conversationId: String,
        turnId: String,
        generationId: String,
        responseId: String,
        seq: Int,
        playedBytes: Int = 0,
        playedDurationMs: Int = 0,
        reason: String = "user_interrupt"
    ) -> RealtimeEventEnvelope {
        RealtimeEventEnvelope(
            conversationId: conversationId,
            turnId: turnId,
            generationId: generationId,
            responseId: responseId,
            seq: seq,
            type: "response.cancel",
            payloadDict: [
                "played_bytes": playedBytes,
                "played_duration_ms": playedDurationMs,
                "reason": reason
            ]
        )
    }

    static func conversationOpen(
        conversationId: String,
        seq: Int = 0
    ) -> RealtimeEventEnvelope {
        RealtimeEventEnvelope(
            conversationId: conversationId,
            turnId: "",
            seq: seq,
            type: "conversation.open"
        )
    }

    static func conversationClose(
        conversationId: String,
        seq: Int,
        reason: String = "user_exit"
    ) -> RealtimeEventEnvelope {
        RealtimeEventEnvelope(
            conversationId: conversationId,
            turnId: "",
            seq: seq,
            type: "conversation.close",
            payloadDict: ["reason": reason]
        )
    }

    static func conversationWillExpire(
        conversationId: String,
        seq: Int
    ) -> RealtimeEventEnvelope {
        RealtimeEventEnvelope(
            conversationId: conversationId,
            turnId: "",
            seq: seq,
            type: "conversation.will_expire"
        )
    }

    // MARK: - Validation

    var isValid: Bool {
        guard schemaVersion == Self.currentSchemaVersion else { return false }
        guard UUID(uuidString: eventId) != nil else { return false }
        guard UUID(uuidString: conversationId) != nil else { return false }
        if !turnId.isEmpty && UUID(uuidString: turnId) == nil { return false }
        if let gid = generationId, UUID(uuidString: gid) == nil { return false }
        if let rid = responseId, UUID(uuidString: rid) == nil { return false }
        guard seq >= 0 else { return false }
        guard !type.isEmpty else { return false }
        guard createdAtMs > 0 else { return false }
        return true
    }

    var logDescription: String {
        let gen = generationId?.prefix(8) ?? "nil"
        let resp = responseId?.prefix(8) ?? "nil"
        return "Envelope(conv: \(conversationId.prefix(8))…, turn: \(turnId.prefix(8))…, gen: \(gen), resp: \(resp), type: \(type), seq: \(seq))"
    }
}

// MARK: - RealtimeEnvelopeFlag

/// Wire-format levers for the ESS-571 conversation identity rollout.
///
/// Phase 0 (current): the flat Bridge wire shape stays authoritative and each
/// uplink frame additionally carries `conversation_id` / `turn_id`. The v1
/// unified envelope is defined and tested, but is not yet the wire format.
///
/// Migration order (per ESS-543 v1.2 §1.1): ESS-541 → ESS-537 → dual-write →
/// dual-read verification → delete old keys.
///
/// ESS-832: this type previously declared `useV1Envelope` /
/// `preferEnvelopeOnReceive`, which no code ever read — they described a
/// rollback lever that did not exist. Only a flag the encoder actually reads
/// belongs here.
enum RealtimeEnvelopeFlag {
    /// Whether uplink frames carry the additive `conversation_id` / `turn_id`
    /// keys alongside the legacy flat-wire fields.
    ///
    /// Read by `RealtimeBridgeWireCodec.encode(_:)`. Set to `false` to fall
    /// back to the pre-ESS-571 wire shape without reverting the identity model
    /// — the escape hatch for a receiver that rejects unknown keys.
    ///
    /// Compile-time constant during Phase 0; change to `var` only when runtime
    /// switching is actually needed.
    static let dualWriteConversationIds: Bool = true
}
